# Generated by Django 3.1.4 on 2020-12-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postflower',
            name='title_ar',
        ),
    ]
